#!/usr/bin/python2.3
# -*- coding: utf-8 -*-
#
# This script creates symlinks for anonymous BOINC applications.
# Copyright © 2006 Debian BOINC Maintainers
#                  <pkg-boinc-devel@lists.alioth.debian.org>
#
# This file is licensed under the terms of the GNU General Public License,
# Version 2 or any later version published by the Free Software Foundation.
#
# $Id$

import optparse
import os
import sys

app_info_dir = '/usr/share/boinc-client/app_info/'

def main():
    if not os.path.isdir(app_info_dir):
        sys.exit(0)

    opts = parse_options()

    projects = {}

    for file in os.listdir(app_info_dir):
        if file.endswith('.py'):
            if opts.project == '' or file == opts.project+'.py':
                execfile(app_info_dir + file)

    for project in projects:
        for url in projects[project]['urls']:
            project_dir = opts.data_dir + '/projects/' + url + '/'

            if opts.create_symlink == True:
                try:
                    os.makedirs(project_dir)
                except OSError:
                    pass

            renew_or_remove_symlink(projects[project]['app_info'],
                project_dir + 'app_info.xml', opts.create_symlink)

            for app in projects[project]['apps']:
                renew_or_remove_symlink(app,
                    project_dir + os.path.basename(app), opts.create_symlink)
    return

def renew_or_remove_symlink(src, dst, create_symlink):
    if os.path.isfile(dst) and not os.path.islink(dst):
        return
    elif os.path.islink(dst):
        os.remove(dst)

    if create_symlink == True:
        os.symlink(src, dst)

    return

def parse_options():
    parser = optparse.OptionParser()

    parser.add_option('--create', action='store_true',
        dest='create_symlink',
        help='create symlinks and project directories')

    parser.add_option('--remove', action='store_false',
        dest='create_symlink', help='remove symlinks')

    parser.add_option('--data-dir', dest='data_dir',
        default='', metavar='DIR',
        help='destination directory for the symlinks')

    parser.add_option('--project', dest='project',
        default='', metavar='PROJECT',
        help='create only symlinks for project PROJECT')

    parser.set_defaults(create_symlink=True)
    (opts, args) = parser.parse_args()

    if opts.data_dir == '':
        parser.error("option '--data-dir' is mandatory")

    return opts

if __name__ == '__main__':
    main()
