debian/bug/boinc-client/script      usr/share/bug/boinc-client
debian/conffiles/*                  etc/boinc-client
debian/extra/bash/*                 etc/bash_completion.d
debian/extra/udev-cpu_share         usr/share/boinc-client
debian/extra/update-boinc-applinks  usr/bin
client/switcher                     usr/lib/boinc-client
client/boinc			    usr/bin
client/boinccmd			    usr/bin
usr/share/locale/*/BOINC-Client.mo
