usr/include/boinc
usr/lib/lib*         usr/lib

#api/graphics_data.h             usr/include/boinc/api
#api/reduce.h                    usr/include/boinc/api
#api/boinc_gl.h                  usr/include/boinc/api
#api/txf_util.h                  usr/include/boinc/api
#lib/md5_file.h                  usr/include/boinc/lib
#lib/procinfo.h                  usr/include/boinc/lib
#lib/str_replace.h               usr/include/boinc
#lib/coproc.h                    usr/include/boinc

# The two below are redundant but seem requested by sample code
lib/*.h	                        usr/include/boinc/lib
api/*.h                         usr/include/boinc/api

# no longer available
#lib/cal.h			usr/include/boinc

config.h			usr/include/boinc
Makefile.am                     usr/share/boinc-dev
