usr/include/boinc/*  usr/include/boinc
usr/lib/lib*         usr/lib

api/graphics_data.h             usr/include/boinc/api
api/reduce.h                    usr/include/boinc/api
api/boinc_gl.h                  usr/include/boinc/api
api/txf_util.h                  usr/include/boinc/api
lib/md5_file.h                  usr/include/boinc/lib
lib/str_replace.h		usr/include/boinc
lib/coproc.h                    usr/include/boinc

# no longer available
#lib/cal.h			usr/include/boinc

config.h			usr/include/boinc
Makefile.am                     usr/share/boinc-dev
