#!/usr/bin/env python

# -*- mode: python; python-indent: 4; -*-

## $Id: parse_config 11116 2006-09-06 17:18:51Z boincadm $

'''
A program to pass config file settings to calling programs via stdout

'''

import configxml
import sys, os

program_path = os.path.realpath(os.path.dirname(sys.argv[0]))
config_filename = os.path.realpath(os.path.join(program_path, '../config.xml'))
config = configxml.ConfigFile(config_filename).read()
print config.config.__dict__.get(sys.argv[1])
